version: '3'
services:
  project-db:
    image: "postgres" # use latest official postgres version
    container_name: postgres-project-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
      - database-data:/var/lib/postgresql/project-database/data/
    ports:
      - '5432:5432'
volumes:
  database-data:
